
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/ming/.cache/JetBrains/RemoteDev/dist/0cd704f641a40_CLion-2024.1.5/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "/home/ming/zephyrproject/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/ming/zephyrproject/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "/home/ming/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/ming/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:117 (include_boilerplate)"
      - "CMakeLists.txt:5 (find_package)"
    message: |
      The target system is: Generic - 3.5.99 - arm
      The host system is: Linux - 6.6.40-amd64-desktop-hwe - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/home/ming/.cache/JetBrains/RemoteDev/dist/0cd704f641a40_CLion-2024.1.5/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/home/ming/.cache/JetBrains/RemoteDev/dist/0cd704f641a40_CLion-2024.1.5/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/home/ming/.cache/JetBrains/RemoteDev/dist/0cd704f641a40_CLion-2024.1.5/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/ming/zephyrproject/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/ming/zephyrproject/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "/home/ming/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/ming/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:117 (include_boilerplate)"
      - "CMakeLists.txt:5 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /home/ming/zephyr-sdk-0.16.8/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      /home/ming/zephyr-sdk-0.16.8/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld: /home/ming/zephyr-sdk-0.16.8/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/lib/libc.a(lib_a-exit.o): in function `exit':
      exit.c:(.text.exit+0x34): undefined reference to `_exit'
      collect2: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/home/ming/.cache/JetBrains/RemoteDev/dist/0cd704f641a40_CLion-2024.1.5/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/home/ming/.cache/JetBrains/RemoteDev/dist/0cd704f641a40_CLion-2024.1.5/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/home/ming/.cache/JetBrains/RemoteDev/dist/0cd704f641a40_CLion-2024.1.5/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/ming/zephyrproject/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/ming/zephyrproject/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "/home/ming/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/ming/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:117 (include_boilerplate)"
      - "CMakeLists.txt:5 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /home/ming/zephyr-sdk-0.16.8/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is GNU, found in:
        /home/ming/zephyrproject/zephyr/samples/modu_test/frist_module/cmake-build-zephyr/CMakeFiles/3.28.6/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/home/ming/.cache/JetBrains/RemoteDev/dist/0cd704f641a40_CLion-2024.1.5/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/home/ming/.cache/JetBrains/RemoteDev/dist/0cd704f641a40_CLion-2024.1.5/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/home/ming/.cache/JetBrains/RemoteDev/dist/0cd704f641a40_CLion-2024.1.5/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/ming/zephyrproject/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/ming/zephyrproject/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "/home/ming/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/ming/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:117 (include_boilerplate)"
      - "CMakeLists.txt:5 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: /home/ming/zephyr-sdk-0.16.8/arm-zephyr-eabi/bin/arm-zephyr-eabi-g++ 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      /home/ming/zephyr-sdk-0.16.8/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld: /home/ming/zephyr-sdk-0.16.8/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/lib/libc.a(lib_a-exit.o): in function `exit':
      exit.c:(.text.exit+0x34): undefined reference to `_exit'
      collect2: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/home/ming/.cache/JetBrains/RemoteDev/dist/0cd704f641a40_CLion-2024.1.5/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/home/ming/.cache/JetBrains/RemoteDev/dist/0cd704f641a40_CLion-2024.1.5/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/home/ming/.cache/JetBrains/RemoteDev/dist/0cd704f641a40_CLion-2024.1.5/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/ming/zephyrproject/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/ming/zephyrproject/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "/home/ming/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/ming/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:117 (include_boilerplate)"
      - "CMakeLists.txt:5 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /home/ming/zephyr-sdk-0.16.8/arm-zephyr-eabi/bin/arm-zephyr-eabi-g++ 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is GNU, found in:
        /home/ming/zephyrproject/zephyr/samples/modu_test/frist_module/cmake-build-zephyr/CMakeFiles/3.28.6/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/home/ming/.cache/JetBrains/RemoteDev/dist/0cd704f641a40_CLion-2024.1.5/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1155 (message)"
      - "/home/ming/.cache/JetBrains/RemoteDev/dist/0cd704f641a40_CLion-2024.1.5/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineASMCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/ming/zephyrproject/zephyr/cmake/modules/kernel.cmake:134 (enable_language)"
      - "/home/ming/zephyrproject/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "/home/ming/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/ming/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:117 (include_boilerplate)"
      - "CMakeLists.txt:5 (find_package)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      arm-zephyr-eabi-gcc (Zephyr SDK 0.16.8) 12.2.0
      Copyright (C) 2022 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
...
